name: Android Lint

on:
  push:
  pull_request:
    branches-ignore:
      - 'master'

jobs:
  checkLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Run Linter
        run: ./gradlew lint
      - name: Upload Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Lint Reports
          path: ~/**/build/reports/
          retention-days: 30
